pipeline
{
    agent any
    stages {
        stage('Build'){
            steps{
                echo "Paso Build.."                
            }
        }
        stage('Test'){
            steps{
                echo "Paso Test.."                
            }
        }
        stage('Deploy'){
            steps{
                echo "Paso Deploy.."
                sh "docker-compose down -v"                
                sh "docker-compose up -d --build"                
            }
        }
    }
}